TOP=..
include $(TOP)/configure/CONFIG

DBD = symb.dbd

HTMLS_DIR = .
HTMLS += devSymb.html

Symb_SRCS += devAiSymb.c
Symb_SRCS += devAoSymb.c
Symb_SRCS += devBiSymb.c
Symb_SRCS += devBoSymb.c
Symb_SRCS += devLiSymb.c
Symb_SRCS += devLoSymb.c
Symb_SRCS += devMbbiSymb.c
Symb_SRCS += devMbboSymb.c
Symb_SRCS += devMbboSymbRaw.c
Symb_SRCS += devSiSymb.c
Symb_SRCS += devSoSymb.c
Symb_SRCS += devSymbFind.c
Symb_SRCS += devWfSymb.c


INC += devSymbTable.h

Symb_SRCS += devSymbTable.c

LIBRARY_IOC = Symb

include $(TOP)/configure/RULES
