sudo: false
dist: trusty
language: c
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
env:
 - BASE=3.14 STATIC=shared RTEMS=4.10
 - BASE=3.15 STATIC=shared RTEMS=4.10
 - BASE=3.16 STATIC=shared RTEMS=4.10
 - BASE=3.16 STATIC=static
install: ./build-deps.sh
script:
 - make -j2
 - make tapfiles
 - find . -name '*.tap' -print0 | xargs -0 -n1 prove -e cat -f
